ALTER TABLE Users ADD COLUMN name VARCHAR(255) NULL AFTER user_id;
ALTER TABLE Users ADD COLUMN email VARCHAR(255) NULL AFTER name;
ALTER TABLE Users ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

UPDATE Users SET email = CONCAT(username, '@demo.com'), name = username;

ALTER TABLE Users MODIFY COLUMN name VARCHAR(255) NOT NULL;
ALTER TABLE Users ADD UNIQUE(email);
